"""add_prescriber_and_pharmacy_to_medication

Revision ID: 3bd787d33e7d
Revises: ac902504d74c
Create Date: 2025-09-21 20:32:56.052792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd787d33e7d'
down_revision: Union[str, None] = 'ac902504d74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('prescriber_id', sa.Integer(), nullable=True))
    op.add_column('medication', sa.Column('pharmacy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medication', 'providers', ['prescriber_id'], ['id'])
    op.create_foreign_key(None, 'medication', 'businesses', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medication', type_='foreignkey')
    op.drop_constraint(None, 'medication', type_='foreignkey')
    op.drop_column('medication', 'pharmacy_id')
    op.drop_column('medication', 'prescriber_id')
    # ### end Alembic commands ###
