"""add_organizations_and_patient_access

Revision ID: dd662365b6ff
Revises: 20260130_business_types
Create Date: 2026-01-31 23:35:54.225113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd662365b6ff'
down_revision: Union[str, None] = '20260130_business_types'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('org_type', sa.Enum('PERSONAL', 'NURSING_AGENCY', 'HOSPICE', 'HOME_HEALTH', 'HOSPITAL', 'CLINIC', 'OTHER', name='organizationtype'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_memberships_id'), 'organization_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('patient_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('access_level', sa.Enum('OWNER', 'ADMIN', 'CAREGIVER', 'VIEWER', name='accesslevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_by_org_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_access_id'), 'patient_access', ['id'], unique=False)
    op.create_index(op.f('ix_patient_access_organization_id'), 'patient_access', ['organization_id'], unique=False)
    op.create_index(op.f('ix_patient_access_patient_id'), 'patient_access', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_access_user_id'), 'patient_access', ['user_id'], unique=False)
    op.add_column('patients', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('creating_org_id', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key('fk_patients_creating_org', 'patients', 'organizations', ['creating_org_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_patients_owner_user', 'patients', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_patients_owner_user', 'patients', type_='foreignkey')
    op.drop_constraint('fk_patients_creating_org', 'patients', type_='foreignkey')
    op.drop_column('patients', 'claimed_at')
    op.drop_column('patients', 'creating_org_id')
    op.drop_column('patients', 'owner_user_id')
    op.drop_index(op.f('ix_patient_access_user_id'), table_name='patient_access')
    op.drop_index(op.f('ix_patient_access_patient_id'), table_name='patient_access')
    op.drop_index(op.f('ix_patient_access_organization_id'), table_name='patient_access')
    op.drop_index(op.f('ix_patient_access_id'), table_name='patient_access')
    op.drop_table('patient_access')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.execute("DROP TYPE IF EXISTS accesslevel")
    op.execute("DROP TYPE IF EXISTS organizationtype")
    # ### end Alembic commands ###
